[package]
name = "vfiles-rsync"
publish = ["crates-io"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
vfiles-domain = { path = "../vfiles-domain" }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }

[lints]
workspace = true
