[package]
name = "vfiles-bin"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "vfiles"
path = "src/main.rs"

[dependencies]
vfiles-app = { path = "../vfiles-app" }
vfiles-config = { path = "../vfiles-config" }
vfiles-domain = { path = "../vfiles-domain" }
async-trait.workspace = true
vfiles-ftp = { path = "../vfiles-ftp" }
vfiles-webdav = { path = "../vfiles-webdav" }
vfiles-rsync = { path = "../vfiles-rsync" }
vfiles-s3 = { path = "../vfiles-s3" }
vfiles-http = { path = "../vfiles-http" }
vfiles-infra-fs = { path = "../vfiles-infra-fs" }
vfiles-infra-sqlite = { path = "../vfiles-infra-sqlite" }

anyhow.workspace = true
axum.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
tower.workspace = true
uuid.workspace = true
s3s = "0.16"

[dev-dependencies]
camino.workspace = true
tempfile.workspace = true
tokio.workspace = true

[features]
embed = ["vfiles-http/embed"]
